# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'i18n'
gem 'sinatra'
gem 'slim'

group :development do
  gem 'byebug'
  gem 'rack-test'
  gem "rspec"
end
